#+TITLE Tests for single sign on authentication

* Weblogic and OAuth

  Weblogic doesn't provide a OAuth authentication provider out of the box. This means we need to create a custom implementation.

** TODO Create simple Authentication Provider
   
   [[https://docs.oracle.com/middleware/1221/wls/DEVSP/toc.htm][Official Documentation]]
   [[https://medium.com/@pubudu2013101/custom-authentication-provider-in-web-logic-12c-5e6ca4667149][Example Implementation]], this seems to just use samples not real OAuth2 authentication
  
*** Setup project

    Initiate maven repository
    #+BEGIN_SRC sh
      mvn archetype:generate  -DarchetypeGroupId=org.apache.maven.archetypes  -DgroupId=be.vercapi.ouath2provider  -DartifactId=OAuthProvider -Dversion=0.1-SNAPSHOT
    #+END_SRC

** TODO [#B] Autentication Provider needs to authenticate with a OAuth token

   The Authentication Provider needs to use the Authorization Code Grant. [[https://tools.ietf.org/html/rfc6749#section-4.2][RFC 6749, 4.1]]

* APIGEE and  SAML

  [[https://tools.ietf.org/html/rfc7522][RFC 7522]] Describes a way to use a SAML Assertion for requesting a OAuth2 token.

  Basically SAML is used to authenticate OAuth2 to authorize. This also ensures that existing SAML services can still be used.
  This [[https://www.slideshare.net/apigee/managing-identities-in-the-world-of-apis][presentation]] gives a high level example.

  APIGEE Seems able to work with SAML as show [[https://apigee.com/about/tags/saml-0][here]]. But is this sufficient?
  This [[https://github.com/srinandan/rfc7522-saml-profile][repository]] is a custom implementation of RFC 7522.

  

  

  
